  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
 import 'package:firebase_core/firebase_core.dart';
 import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
   
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3oT6EWkVXTn9XlRVUdnGjbik9JyMcCfo',
    appId: '1:317260225578:web:c1a37573a94057614bf753',
    messagingSenderId: '317260225578',
    projectId: 'flutterchat-2eea1',
    authDomain: 'flutterchat-2eea1.firebaseapp.com',
    storageBucket: 'flutterchat-2eea1.appspot.com',
    measurementId: 'G-FHVHNG6NXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt3gGG1McFcEn0towBRTt7n7_nKAS9300',
    appId: '1:317260225578:android:6f47959e7a065a824bf753',
    messagingSenderId: '317260225578',
    projectId: 'flutterchat-2eea1',
    storageBucket: 'flutterchat-2eea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdatb9mb-D8TjtSY_D6cLBe6hZq3YW2JE',
    appId: '1:317260225578:ios:ec05c95d31ab06344bf753',
    messagingSenderId: '317260225578',
    projectId: 'flutterchat-2eea1',
    storageBucket: 'flutterchat-2eea1.appspot.com',
    iosClientId: '317260225578-8kovlbpbk7als1n8kc7b8msb307msqge.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdatb9mb-D8TjtSY_D6cLBe6hZq3YW2JE',
    appId: '1:317260225578:ios:ec05c95d31ab06344bf753',
    messagingSenderId: '317260225578',
    projectId: 'flutterchat-2eea1',
    storageBucket: 'flutterchat-2eea1.appspot.com',
    iosClientId: '317260225578-8kovlbpbk7als1n8kc7b8msb307msqge.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
